version: '3'
services:
  app:
    build:
      context: '.'
    container_name: 'backend-password-manager'
    volumes:
      - '.:/usr/src/app'
    ports:
      - '${PORT:-10000}:10000'
    environment:
      NODE_ENV: 'development'
    command: 'npm run dev'
